// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif


RcppExport SEXP _rcpp_module_boot_stan_fit4glm_pp_bernoulli_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4glm_pp_bernoulli_post_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4glm_pp_fixed_bernoulli_post_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4glm_pp_fixed_gamma_post_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4glm_pp_fixed_invgaussian_post_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4glm_pp_fixed_poisson_post_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4glm_pp_gamma_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4glm_pp_gamma_post_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4glm_pp_gaussian_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4glm_pp_gaussian_post_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4glm_pp_invgaussian_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4glm_pp_invgaussian_post_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4glm_pp_poisson_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4glm_pp_poisson_post_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4lm_npp_gaussian_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4lm_pp_fixed_gaussian_post_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4lm_pp_gaussian_post_mod();

static const R_CallMethodDef CallEntries[] = {
    {"_rcpp_module_boot_stan_fit4glm_pp_bernoulli_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4glm_pp_bernoulli_mod, 0},
    {"_rcpp_module_boot_stan_fit4glm_pp_bernoulli_post_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4glm_pp_bernoulli_post_mod, 0},
    {"_rcpp_module_boot_stan_fit4glm_pp_fixed_bernoulli_post_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4glm_pp_fixed_bernoulli_post_mod, 0},
    {"_rcpp_module_boot_stan_fit4glm_pp_fixed_gamma_post_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4glm_pp_fixed_gamma_post_mod, 0},
    {"_rcpp_module_boot_stan_fit4glm_pp_fixed_invgaussian_post_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4glm_pp_fixed_invgaussian_post_mod, 0},
    {"_rcpp_module_boot_stan_fit4glm_pp_fixed_poisson_post_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4glm_pp_fixed_poisson_post_mod, 0},
    {"_rcpp_module_boot_stan_fit4glm_pp_gamma_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4glm_pp_gamma_mod, 0},
    {"_rcpp_module_boot_stan_fit4glm_pp_gamma_post_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4glm_pp_gamma_post_mod, 0},
    {"_rcpp_module_boot_stan_fit4glm_pp_gaussian_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4glm_pp_gaussian_mod, 0},
    {"_rcpp_module_boot_stan_fit4glm_pp_gaussian_post_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4glm_pp_gaussian_post_mod, 0},
    {"_rcpp_module_boot_stan_fit4glm_pp_invgaussian_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4glm_pp_invgaussian_mod, 0},
    {"_rcpp_module_boot_stan_fit4glm_pp_invgaussian_post_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4glm_pp_invgaussian_post_mod, 0},
    {"_rcpp_module_boot_stan_fit4glm_pp_poisson_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4glm_pp_poisson_mod, 0},
    {"_rcpp_module_boot_stan_fit4glm_pp_poisson_post_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4glm_pp_poisson_post_mod, 0},
    {"_rcpp_module_boot_stan_fit4lm_npp_gaussian_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4lm_npp_gaussian_mod, 0},
    {"_rcpp_module_boot_stan_fit4lm_pp_fixed_gaussian_post_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4lm_pp_fixed_gaussian_post_mod, 0},
    {"_rcpp_module_boot_stan_fit4lm_pp_gaussian_post_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4lm_pp_gaussian_post_mod, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_glmnpp(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
